/* automatically generated by rust-bindgen */

pub type __u_char = ::libc::c_uchar;
pub type __u_short = ::libc::c_ushort;
pub type __u_int = ::libc::c_uint;
pub type __u_long = ::libc::c_ulong;
pub type __int8_t = ::libc::c_char;
pub type __uint8_t = ::libc::c_uchar;
pub type __int16_t = ::libc::c_short;
pub type __uint16_t = ::libc::c_ushort;
pub type __int32_t = ::libc::c_int;
pub type __uint32_t = ::libc::c_uint;
pub type __int64_t = ::libc::c_long;
pub type __uint64_t = ::libc::c_ulong;
pub type __quad_t = ::libc::c_long;
pub type __u_quad_t = ::libc::c_ulong;
pub type __dev_t = ::libc::c_ulong;
pub type __uid_t = ::libc::c_uint;
pub type __gid_t = ::libc::c_uint;
pub type __ino_t = ::libc::c_ulong;
pub type __ino64_t = ::libc::c_ulong;
pub type __mode_t = ::libc::c_uint;
pub type __nlink_t = ::libc::c_ulong;
pub type __off_t = ::libc::c_long;
pub type __off64_t = ::libc::c_long;
pub type __pid_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed1 {
    pub __val: [::libc::c_int; 2usize],
}
impl ::std::clone::Clone for Struct_Unnamed1 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed1 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __fsid_t = Struct_Unnamed1;
pub type __clock_t = ::libc::c_long;
pub type __rlim_t = ::libc::c_ulong;
pub type __rlim64_t = ::libc::c_ulong;
pub type __id_t = ::libc::c_uint;
pub type __time_t = ::libc::c_long;
pub type __useconds_t = ::libc::c_uint;
pub type __suseconds_t = ::libc::c_long;
pub type __daddr_t = ::libc::c_int;
pub type __key_t = ::libc::c_int;
pub type __clockid_t = ::libc::c_int;
pub type __timer_t = *mut ::libc::c_void;
pub type __blksize_t = ::libc::c_long;
pub type __blkcnt_t = ::libc::c_long;
pub type __blkcnt64_t = ::libc::c_long;
pub type __fsblkcnt_t = ::libc::c_ulong;
pub type __fsblkcnt64_t = ::libc::c_ulong;
pub type __fsfilcnt_t = ::libc::c_ulong;
pub type __fsfilcnt64_t = ::libc::c_ulong;
pub type __fsword_t = ::libc::c_long;
pub type __ssize_t = ::libc::c_long;
pub type __syscall_slong_t = ::libc::c_long;
pub type __syscall_ulong_t = ::libc::c_ulong;
pub type __loff_t = __off64_t;
pub type __qaddr_t = *mut __quad_t;
pub type __caddr_t = *mut ::libc::c_char;
pub type __intptr_t = ::libc::c_long;
pub type __socklen_t = ::libc::c_uint;
pub type time_t = __time_t;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_timeval {
    pub tv_sec: __time_t,
    pub tv_usec: __suseconds_t,
}
impl ::std::clone::Clone for Struct_timeval {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_timeval {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __sig_atomic_t = ::libc::c_int;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed2 {
    pub __val: [::libc::c_ulong; 16usize],
}
impl ::std::clone::Clone for Struct_Unnamed2 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed2 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __sigset_t = Struct_Unnamed2;
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_timespec {
    pub tv_sec: __time_t,
    pub tv_nsec: __syscall_slong_t,
}
impl ::std::clone::Clone for Struct_timespec {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_timespec {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type suseconds_t = __suseconds_t;
pub type __fd_mask = ::libc::c_long;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed3 {
    pub __fds_bits: [__fd_mask; 16usize],
}
impl ::std::clone::Clone for Struct_Unnamed3 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed3 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type fd_set = Struct_Unnamed3;
pub type fd_mask = __fd_mask;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_timezone {
    pub tz_minuteswest: ::libc::c_int,
    pub tz_dsttime: ::libc::c_int,
}
impl ::std::clone::Clone for Struct_timezone {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_timezone {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __timezone_ptr_t = *mut Struct_timezone;
pub type Enum___itimer_which = ::libc::c_uint;
pub const ITIMER_REAL: ::libc::c_uint = 0;
pub const ITIMER_VIRTUAL: ::libc::c_uint = 1;
pub const ITIMER_PROF: ::libc::c_uint = 2;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_itimerval {
    pub it_interval: Struct_timeval,
    pub it_value: Struct_timeval,
}
impl ::std::clone::Clone for Struct_itimerval {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_itimerval {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type __itimer_which_t = ::libc::c_int;
pub type TangoDevLong = ::libc::c_int;
pub type TangoDevULong = ::libc::c_uint;
pub type TangoDevLong64 = ::libc::c_long;
pub type TangoDevULong64 = ::libc::c_ulong;
pub type Enum_Unnamed4 = ::libc::c_uint;
pub const DEV_VOID: ::libc::c_uint = 0;
pub const DEV_BOOLEAN: ::libc::c_uint = 1;
pub const DEV_SHORT: ::libc::c_uint = 2;
pub const DEV_LONG: ::libc::c_uint = 3;
pub const DEV_FLOAT: ::libc::c_uint = 4;
pub const DEV_DOUBLE: ::libc::c_uint = 5;
pub const DEV_USHORT: ::libc::c_uint = 6;
pub const DEV_ULONG: ::libc::c_uint = 7;
pub const DEV_STRING: ::libc::c_uint = 8;
pub const DEVVAR_CHARARRAY: ::libc::c_uint = 9;
pub const DEVVAR_SHORTARRAY: ::libc::c_uint = 10;
pub const DEVVAR_LONGARRAY: ::libc::c_uint = 11;
pub const DEVVAR_FLOATARRAY: ::libc::c_uint = 12;
pub const DEVVAR_DOUBLEARRAY: ::libc::c_uint = 13;
pub const DEVVAR_USHORTARRAY: ::libc::c_uint = 14;
pub const DEVVAR_ULONGARRAY: ::libc::c_uint = 15;
pub const DEVVAR_STRINGARRAY: ::libc::c_uint = 16;
pub const DEVVAR_LONGSTRINGARRAY: ::libc::c_uint = 17;
pub const DEVVAR_DOUBLESTRINGARRAY: ::libc::c_uint = 18;
pub const DEV_STATE: ::libc::c_uint = 19;
pub const CONST_DEV_STRING: ::libc::c_uint = 20;
pub const DEVVAR_BOOLEANARRAY: ::libc::c_uint = 21;
pub const DEV_UCHAR: ::libc::c_uint = 22;
pub const DEV_LONG64: ::libc::c_uint = 23;
pub const DEV_ULONG64: ::libc::c_uint = 24;
pub const DEVVAR_LONG64ARRAY: ::libc::c_uint = 25;
pub const DEVVAR_ULONG64ARRAY: ::libc::c_uint = 26;
pub const DEV_INT: ::libc::c_uint = 27;
pub const DEV_ENCODED: ::libc::c_uint = 28;
pub type TangoDataType = Enum_Unnamed4;
pub type Enum_Unnamed5 = ::libc::c_uint;
pub const ON: ::libc::c_uint = 0;
pub const OFF: ::libc::c_uint = 1;
pub const CLOSE: ::libc::c_uint = 2;
pub const OPEN: ::libc::c_uint = 3;
pub const INSERT: ::libc::c_uint = 4;
pub const EXTRACT: ::libc::c_uint = 5;
pub const MOVING: ::libc::c_uint = 6;
pub const STANDBY: ::libc::c_uint = 7;
pub const FAULT: ::libc::c_uint = 8;
pub const INIT: ::libc::c_uint = 9;
pub const RUNNING: ::libc::c_uint = 10;
pub const ALARM: ::libc::c_uint = 11;
pub const DISABLE: ::libc::c_uint = 12;
pub const UNKNOWN: ::libc::c_uint = 13;
pub type TangoDevState = Enum_Unnamed5;
pub type Enum_Unnamed6 = ::libc::c_uint;
pub const ATTR_VALID: ::libc::c_uint = 0;
pub const ATTR_INVALID: ::libc::c_uint = 1;
pub const ATTR_ALARM: ::libc::c_uint = 2;
pub const ATTR_CHANGING: ::libc::c_uint = 3;
pub const ATTR_WARNING: ::libc::c_uint = 4;
pub type AttrQuality = Enum_Unnamed6;
pub type Enum_Unnamed7 = ::libc::c_uint;
pub const READ: ::libc::c_uint = 0;
pub const READ_WITH_WRITE: ::libc::c_uint = 1;
pub const WRITE: ::libc::c_uint = 2;
pub const READ_WRITE: ::libc::c_uint = 3;
pub type AttrWriteType = Enum_Unnamed7;
pub type Enum_Unnamed8 = ::libc::c_uint;
pub const SCALAR: ::libc::c_uint = 0;
pub const SPECTRUM: ::libc::c_uint = 1;
pub const IMAGE: ::libc::c_uint = 2;
pub type AttrDataFormat = Enum_Unnamed8;
pub type Enum_Unnamed9 = ::libc::c_uint;
pub const OPERATOR: ::libc::c_uint = 0;
pub const EXPERT: ::libc::c_uint = 1;
pub type DispLevel = Enum_Unnamed9;
pub type Enum_Unnamed10 = ::libc::c_uint;
pub const WARN: ::libc::c_uint = 0;
pub const ERR: ::libc::c_uint = 1;
pub const PANIC: ::libc::c_uint = 2;
pub type ErrSeverity = Enum_Unnamed10;
pub type Enum_Unnamed11 = ::libc::c_uint;
pub const DEV: ::libc::c_uint = 0;
pub const CACHE: ::libc::c_uint = 1;
pub const CACHE_DEV: ::libc::c_uint = 2;
pub type DevSource = Enum_Unnamed11;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed12 {
    pub encoded_format: *mut ::libc::c_char,
    pub encoded_length: ::libc::c_uint,
    pub encoded_data: *mut ::libc::c_uchar,
}
impl ::std::clone::Clone for Struct_Unnamed12 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed12 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type TangoDevEncoded = Struct_Unnamed12;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed13 {
    pub length: ::libc::c_uint,
    pub sequence: *mut u8,
}
impl ::std::clone::Clone for Struct_Unnamed13 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed13 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarBoolArray = Struct_Unnamed13;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed14 {
    pub length: ::libc::c_uint,
    pub sequence: *mut ::libc::c_uchar,
}
impl ::std::clone::Clone for Struct_Unnamed14 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed14 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarCharArray = Struct_Unnamed14;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed15 {
    pub length: ::libc::c_uint,
    pub sequence: *mut ::libc::c_short,
}
impl ::std::clone::Clone for Struct_Unnamed15 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed15 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarShortArray = Struct_Unnamed15;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed16 {
    pub length: ::libc::c_uint,
    pub sequence: *mut ::libc::c_ushort,
}
impl ::std::clone::Clone for Struct_Unnamed16 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed16 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarUShortArray = Struct_Unnamed16;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed17 {
    pub length: ::libc::c_uint,
    pub sequence: *mut TangoDevLong,
}
impl ::std::clone::Clone for Struct_Unnamed17 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed17 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarLongArray = Struct_Unnamed17;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed18 {
    pub length: ::libc::c_uint,
    pub sequence: *mut TangoDevULong,
}
impl ::std::clone::Clone for Struct_Unnamed18 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed18 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarULongArray = Struct_Unnamed18;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed19 {
    pub length: ::libc::c_uint,
    pub sequence: *mut TangoDevLong64,
}
impl ::std::clone::Clone for Struct_Unnamed19 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed19 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarLong64Array = Struct_Unnamed19;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed20 {
    pub length: ::libc::c_uint,
    pub sequence: *mut TangoDevULong64,
}
impl ::std::clone::Clone for Struct_Unnamed20 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed20 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarULong64Array = Struct_Unnamed20;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed21 {
    pub length: ::libc::c_uint,
    pub sequence: *mut ::libc::c_float,
}
impl ::std::clone::Clone for Struct_Unnamed21 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed21 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarFloatArray = Struct_Unnamed21;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed22 {
    pub length: ::libc::c_uint,
    pub sequence: *mut ::libc::c_double,
}
impl ::std::clone::Clone for Struct_Unnamed22 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed22 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarDoubleArray = Struct_Unnamed22;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed23 {
    pub length: ::libc::c_uint,
    pub sequence: *mut *mut ::libc::c_char,
}
impl ::std::clone::Clone for Struct_Unnamed23 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed23 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarStringArray = Struct_Unnamed23;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed24 {
    pub length: ::libc::c_uint,
    pub sequence: *mut TangoDevState,
}
impl ::std::clone::Clone for Struct_Unnamed24 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed24 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarStateArray = Struct_Unnamed24;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed25 {
    pub length: ::libc::c_uint,
    pub sequence: *mut TangoDevEncoded,
}
impl ::std::clone::Clone for Struct_Unnamed25 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed25 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarEncodedArray = Struct_Unnamed25;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed26 {
    pub long_length: ::libc::c_uint,
    pub long_sequence: *mut TangoDevLong,
    pub string_length: ::libc::c_uint,
    pub string_sequence: *mut *mut ::libc::c_char,
}
impl ::std::clone::Clone for Struct_Unnamed26 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed26 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarLongStringArray = Struct_Unnamed26;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed27 {
    pub double_length: ::libc::c_uint,
    pub double_sequence: *mut ::libc::c_double,
    pub string_length: ::libc::c_uint,
    pub string_sequence: *mut *mut ::libc::c_char,
}
impl ::std::clone::Clone for Struct_Unnamed27 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed27 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type VarDoubleStringArray = Struct_Unnamed27;
#[repr(C)]
#[derive(Copy)]
pub struct Union_Unnamed28 {
    pub _bindgen_data_: [u64; 2usize],
}
impl Union_Unnamed28 {
    pub unsafe fn bool_arr(&mut self) -> *mut VarBoolArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn char_arr(&mut self) -> *mut VarCharArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn short_arr(&mut self) -> *mut VarShortArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ushort_arr(&mut self) -> *mut VarUShortArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long_arr(&mut self) -> *mut VarLongArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong_arr(&mut self) -> *mut VarULongArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long64_arr(&mut self) -> *mut VarLong64Array {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong64_arr(&mut self) -> *mut VarULong64Array {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn float_arr(&mut self) -> *mut VarFloatArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn double_arr(&mut self) -> *mut VarDoubleArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn string_arr(&mut self) -> *mut VarStringArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn state_arr(&mut self) -> *mut VarStateArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn encoded_arr(&mut self) -> *mut VarEncodedArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for Union_Unnamed28 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Union_Unnamed28 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type TangoAttributeData = Union_Unnamed28;
#[repr(C)]
#[derive(Copy)]
pub struct Union_Unnamed29 {
    pub _bindgen_data_: [u64; 4usize],
}
impl Union_Unnamed29 {
    pub unsafe fn bool_val(&mut self) -> *mut u8 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn short_val(&mut self) -> *mut ::libc::c_short {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ushort_val(&mut self) -> *mut ::libc::c_ushort {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long_val(&mut self) -> *mut ::libc::c_int {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong_val(&mut self) -> *mut ::libc::c_uint {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn float_val(&mut self) -> *mut ::libc::c_float {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn double_val(&mut self) -> *mut ::libc::c_double {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn string_val(&mut self) -> *mut *mut ::libc::c_char {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn state_val(&mut self) -> *mut TangoDevState {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long64_val(&mut self) -> *mut TangoDevLong64 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong64_val(&mut self) -> *mut TangoDevULong64 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn bool_arr(&mut self) -> *mut VarBoolArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn char_arr(&mut self) -> *mut VarCharArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn short_arr(&mut self) -> *mut VarShortArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ushort_arr(&mut self) -> *mut VarUShortArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long_arr(&mut self) -> *mut VarLongArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong_arr(&mut self) -> *mut VarULongArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long64_arr(&mut self) -> *mut VarLong64Array {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong64_arr(&mut self) -> *mut VarULong64Array {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn float_arr(&mut self) -> *mut VarFloatArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn double_arr(&mut self) -> *mut VarDoubleArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn string_arr(&mut self) -> *mut VarStringArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn state_arr(&mut self) -> *mut VarStateArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn encoded_val(&mut self) -> *mut TangoDevEncoded {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long_string_arr(&mut self) -> *mut VarLongStringArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn double_string_arr(&mut self) -> *mut VarDoubleStringArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for Union_Unnamed29 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Union_Unnamed29 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type TangoCommandData = Union_Unnamed29;
#[repr(C)]
#[derive(Copy)]
pub struct Union_Unnamed30 {
    pub _bindgen_data_: [u64; 2usize],
}
impl Union_Unnamed30 {
    pub unsafe fn bool_val(&mut self) -> *mut u8 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn char_val(&mut self) -> *mut ::libc::c_uchar {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn short_val(&mut self) -> *mut ::libc::c_short {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ushort_val(&mut self) -> *mut ::libc::c_ushort {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long_val(&mut self) -> *mut ::libc::c_int {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong_val(&mut self) -> *mut ::libc::c_uint {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn float_val(&mut self) -> *mut ::libc::c_float {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn double_val(&mut self) -> *mut ::libc::c_double {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn string_val(&mut self) -> *mut *mut ::libc::c_char {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long64_val(&mut self) -> *mut TangoDevLong64 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong64_val(&mut self) -> *mut TangoDevULong64 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn short_arr(&mut self) -> *mut VarShortArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ushort_arr(&mut self) -> *mut VarUShortArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long_arr(&mut self) -> *mut VarLongArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong_arr(&mut self) -> *mut VarULongArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn long64_arr(&mut self) -> *mut VarLong64Array {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn ulong64_arr(&mut self) -> *mut VarULong64Array {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn float_arr(&mut self) -> *mut VarFloatArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn double_arr(&mut self) -> *mut VarDoubleArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn string_arr(&mut self) -> *mut VarStringArray {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::clone::Clone for Union_Unnamed30 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Union_Unnamed30 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type TangoPropertyData = Union_Unnamed30;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed31 {
    pub arg_type: TangoDataType,
    pub cmd_data: TangoCommandData,
}
impl ::std::clone::Clone for Struct_Unnamed31 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed31 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type CommandData = Struct_Unnamed31;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed32 {
    pub data_type: TangoDataType,
    pub attr_data: TangoAttributeData,
    pub data_format: AttrDataFormat,
    pub quality: AttrQuality,
    pub nb_read: ::libc::c_long,
    pub name: *mut ::libc::c_char,
    pub dim_x: ::libc::c_int,
    pub dim_y: ::libc::c_int,
    pub time_stamp: Struct_timeval,
}
impl ::std::clone::Clone for Struct_Unnamed32 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed32 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type AttributeData = Struct_Unnamed32;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed33 {
    pub length: ::libc::c_uint,
    pub sequence: *mut AttributeData,
}
impl ::std::clone::Clone for Struct_Unnamed33 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed33 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type AttributeDataList = Struct_Unnamed33;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed34 {
    pub desc: *mut ::libc::c_char,
    pub reason: *mut ::libc::c_char,
    pub origin: *mut ::libc::c_char,
    pub severity: ErrSeverity,
}
impl ::std::clone::Clone for Struct_Unnamed34 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed34 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type DevFailed = Struct_Unnamed34;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed35 {
    pub length: ::libc::c_uint,
    pub sequence: *mut DevFailed,
}
impl ::std::clone::Clone for Struct_Unnamed35 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed35 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type ErrorStack = Struct_Unnamed35;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed36 {
    pub cmd_name: *mut ::libc::c_char,
    pub cmd_tag: ::libc::c_int,
    pub in_type: ::libc::c_int,
    pub out_type: ::libc::c_int,
    pub in_type_desc: *mut ::libc::c_char,
    pub out_type_desc: *mut ::libc::c_char,
    pub disp_level: DispLevel,
}
impl ::std::clone::Clone for Struct_Unnamed36 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed36 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type CommandInfo = Struct_Unnamed36;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed37 {
    pub length: ::libc::c_uint,
    pub sequence: *mut CommandInfo,
}
impl ::std::clone::Clone for Struct_Unnamed37 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed37 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type CommandInfoList = Struct_Unnamed37;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed38 {
    pub name: *mut ::libc::c_char,
    pub writable: AttrWriteType,
    pub data_format: AttrDataFormat,
    pub data_type: TangoDataType,
    pub max_dim_x: ::libc::c_int,
    pub max_dim_y: ::libc::c_int,
    pub description: *mut ::libc::c_char,
    pub label: *mut ::libc::c_char,
    pub unit: *mut ::libc::c_char,
    pub standard_unit: *mut ::libc::c_char,
    pub display_unit: *mut ::libc::c_char,
    pub format: *mut ::libc::c_char,
    pub min_value: *mut ::libc::c_char,
    pub max_value: *mut ::libc::c_char,
    pub min_alarm: *mut ::libc::c_char,
    pub max_alarm: *mut ::libc::c_char,
    pub writable_attr_name: *mut ::libc::c_char,
    pub disp_level: DispLevel,
}
impl ::std::clone::Clone for Struct_Unnamed38 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed38 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type AttributeInfo = Struct_Unnamed38;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed39 {
    pub length: ::libc::c_uint,
    pub sequence: *mut AttributeInfo,
}
impl ::std::clone::Clone for Struct_Unnamed39 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed39 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type AttributeInfoList = Struct_Unnamed39;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed40 {
    pub property_name: *mut ::libc::c_char,
    pub data_type: TangoDataType,
    pub prop_data: TangoPropertyData,
    pub is_empty: u8,
    pub wrong_data_type: u8,
}
impl ::std::clone::Clone for Struct_Unnamed40 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed40 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type DbDatum = Struct_Unnamed40;
#[repr(C)]
#[derive(Copy)]
pub struct Struct_Unnamed41 {
    pub length: ::libc::c_uint,
    pub sequence: *mut DbDatum,
}
impl ::std::clone::Clone for Struct_Unnamed41 {
    fn clone(&self) -> Self { *self }
}
impl ::std::default::Default for Struct_Unnamed41 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
pub type DbData = Struct_Unnamed41;
extern "C" {
    pub fn select(__nfds: ::libc::c_int, __readfds: *mut fd_set,
                  __writefds: *mut fd_set, __exceptfds: *mut fd_set,
                  __timeout: *mut Struct_timeval) -> ::libc::c_int;
    pub fn pselect(__nfds: ::libc::c_int, __readfds: *mut fd_set,
                   __writefds: *mut fd_set, __exceptfds: *mut fd_set,
                   __timeout: *const Struct_timespec,
                   __sigmask: *const __sigset_t) -> ::libc::c_int;
    pub fn gettimeofday(__tv: *mut Struct_timeval, __tz: __timezone_ptr_t)
     -> ::libc::c_int;
    pub fn settimeofday(__tv: *const Struct_timeval,
                        __tz: *const Struct_timezone) -> ::libc::c_int;
    pub fn adjtime(__delta: *const Struct_timeval,
                   __olddelta: *mut Struct_timeval) -> ::libc::c_int;
    pub fn getitimer(__which: __itimer_which_t,
                     __value: *mut Struct_itimerval) -> ::libc::c_int;
    pub fn setitimer(__which: __itimer_which_t,
                     __new: *const Struct_itimerval,
                     __old: *mut Struct_itimerval) -> ::libc::c_int;
    pub fn utimes(__file: *const ::libc::c_char, __tvp: *mut Struct_timeval)
     -> ::libc::c_int;
    pub fn lutimes(__file: *const ::libc::c_char, __tvp: *mut Struct_timeval)
     -> ::libc::c_int;
    pub fn futimes(__fd: ::libc::c_int, __tvp: *mut Struct_timeval)
     -> ::libc::c_int;
    pub fn tango_create_device_proxy(dev_name: *mut ::libc::c_char,
                                     proxy: *mut *mut ::libc::c_void)
     -> *mut ErrorStack;
    pub fn tango_delete_device_proxy(proxy: *mut ::libc::c_void)
     -> *mut ErrorStack;
    pub fn tango_set_timeout_millis(proxy: *mut ::libc::c_void,
                                    millis: ::libc::c_int) -> *mut ErrorStack;
    pub fn tango_get_timeout_millis(proxy: *mut ::libc::c_void,
                                    millis: *mut ::libc::c_int)
     -> *mut ErrorStack;
    pub fn tango_set_source(proxy: *mut ::libc::c_void, source: DevSource)
     -> *mut ErrorStack;
    pub fn tango_get_source(proxy: *mut ::libc::c_void,
                            source: *mut DevSource) -> *mut ErrorStack;
    pub fn tango_lock(proxy: *mut ::libc::c_void) -> *mut ErrorStack;
    pub fn tango_unlock(proxy: *mut ::libc::c_void) -> *mut ErrorStack;
    pub fn tango_is_locked(proxy: *mut ::libc::c_void, is_locked: *mut u8)
     -> *mut ErrorStack;
    pub fn tango_is_locked_by_me(proxy: *mut ::libc::c_void,
                                 is_locked_by_me: *mut u8) -> *mut ErrorStack;
    pub fn tango_locking_status(proxy: *mut ::libc::c_void,
                                lock_status: *mut *mut ::libc::c_char)
     -> *mut ErrorStack;
    pub fn tango_command_query(proxy: *mut ::libc::c_void,
                               cmd_name: *mut ::libc::c_char,
                               cmd_info: *mut CommandInfo) -> *mut ErrorStack;
    pub fn tango_command_list_query(proxy: *mut ::libc::c_void,
                                    cmd_info_list: *mut CommandInfoList)
     -> *mut ErrorStack;
    pub fn tango_command_inout(proxy: *mut ::libc::c_void,
                               cmd_name: *mut ::libc::c_char,
                               argin: *mut CommandData,
                               argout: *mut CommandData) -> *mut ErrorStack;
    pub fn tango_free_CommandData(command_data: *mut CommandData) -> ();
    pub fn tango_free_CommandInfo(command_info: *mut CommandInfo) -> ();
    pub fn tango_free_CommandInfoList(command_info_list: *mut CommandInfoList)
     -> ();
    pub fn tango_get_attribute_list(proxy: *mut ::libc::c_void,
                                    attr_names: *mut VarStringArray)
     -> *mut ErrorStack;
    pub fn tango_get_attribute_config(proxy: *mut ::libc::c_void,
                                      attr_names: *mut VarStringArray,
                                      attr_info_list: *mut AttributeInfoList)
     -> *mut ErrorStack;
    pub fn tango_attribute_list_query(proxy: *mut ::libc::c_void,
                                      attr_info_list: *mut AttributeInfoList)
     -> *mut ErrorStack;
    pub fn tango_read_attribute(proxy: *mut ::libc::c_void,
                                attr_name: *mut ::libc::c_char,
                                argout: *mut AttributeData)
     -> *mut ErrorStack;
    pub fn tango_write_attribute(proxy: *mut ::libc::c_void,
                                 argin: *mut AttributeData)
     -> *mut ErrorStack;
    pub fn tango_read_attributes(proxy: *mut ::libc::c_void,
                                 attr_names: *mut VarStringArray,
                                 argout: *mut AttributeDataList)
     -> *mut ErrorStack;
    pub fn tango_write_attributes(proxy: *mut ::libc::c_void,
                                  argin: *mut AttributeDataList)
     -> *mut ErrorStack;
    pub fn tango_free_AttributeData(attribute_data: *mut AttributeData) -> ();
    pub fn tango_free_AttributeDataList(attribute_data_list:
                                            *mut AttributeDataList) -> ();
    pub fn tango_free_VarStringArray(string_arr: *mut VarStringArray) -> ();
    pub fn tango_free_AttributeInfoList(attribute_info_list:
                                            *mut AttributeInfoList) -> ();
    pub fn tango_free_ErrorStack(error_stack: *mut ErrorStack) -> ();
    pub fn tango_create_database_proxy(db_proxy: *mut *mut ::libc::c_void)
     -> *mut ErrorStack;
    pub fn tango_delete_database_proxy(db_proxy: *mut ::libc::c_void)
     -> *mut ErrorStack;
    pub fn tango_get_device_exported(db_proxy: *mut ::libc::c_void,
                                     name_filter: *mut ::libc::c_char,
                                     dev_list: *mut DbDatum)
     -> *mut ErrorStack;
    pub fn tango_get_device_exported_for_class(db_proxy: *mut ::libc::c_void,
                                               class_name:
                                                   *mut ::libc::c_char,
                                               dev_list: *mut DbDatum)
     -> *mut ErrorStack;
    pub fn tango_get_object_list(db_proxy: *mut ::libc::c_void,
                                 name_filter: *mut ::libc::c_char,
                                 obj_list: *mut DbDatum) -> *mut ErrorStack;
    pub fn tango_get_object_property_list(db_proxy: *mut ::libc::c_void,
                                          obj_name: *mut ::libc::c_char,
                                          name_filter: *mut ::libc::c_char,
                                          prop_list: *mut DbDatum)
     -> *mut ErrorStack;
    pub fn tango_get_property(db_proxy: *mut ::libc::c_void,
                              obj_name: *mut ::libc::c_char,
                              prop_list: *mut DbData) -> *mut ErrorStack;
    pub fn tango_put_property(db_proxy: *mut ::libc::c_void,
                              obj_name: *mut ::libc::c_char,
                              prop_list: *mut DbData) -> *mut ErrorStack;
    pub fn tango_delete_property(db_proxy: *mut ::libc::c_void,
                                 obj_name: *mut ::libc::c_char,
                                 prop_list: *mut DbData) -> *mut ErrorStack;
    pub fn tango_get_device_property(dev_proxy: *mut ::libc::c_void,
                                     prop_list: *mut DbData)
     -> *mut ErrorStack;
    pub fn tango_put_device_property(dev_proxy: *mut ::libc::c_void,
                                     prop_list: *mut DbData)
     -> *mut ErrorStack;
    pub fn tango_delete_device_property(dev_proxy: *mut ::libc::c_void,
                                        prop_list: *mut DbData)
     -> *mut ErrorStack;
    pub fn tango_free_DbDatum(db_datum: *mut DbDatum) -> ();
    pub fn tango_free_DbData(db_data: *mut DbData) -> ();
}
